### ISSUE TITLE
Commentaar op tekst

### ISSUE THREAD

**Issue by pbelmans** [MakeInBelgium/maskermatch#1]
De tekst is nog niet afgewerkt lijkt me, maar hier zijn een paar zaken om zeker niet te vergeten:

* doneer, ipv donneer
* "Je ben een zorgverlener?" -> bent
* link naar website van VAPH (en schrijf het in hoofdletters?)

**Comment by woutervddn** [comment]
fixed in https://github.com/MakeInBelgium/maskermatch/commit/90c332fe59905a521b73c18390245ab817f665c8 and https://github.com/MakeInBelgium/maskermatch/commit/1265653aecd20437d8f6668bad32f0530e9f2c73
