### ISSUE TITLE
Twitter pancarte

### ISSUE THREAD

**Issue by pbelmans** [MakeInBelgium/maskermatch#10]
Cfr. @iworx

> Guys — jullie pancarte / twitter info / … is nog van maakjemondmasker

**Comment by davidcandreva** [comment]
Lijkt me niet beide linken naar https://maskermatch.be/images/og.png volgens de broncode.

**Comment by pbelmans** [comment]
Dat lijkt in orde te zijn. Maar die PNG is 4 megabyte groot (!). Ik zal daar eens me aan de slag gaan :).

**Comment by cloudz** [comment]
Op Twitter -- toen ik de link deed voor iemand - kwam de maakjemondmasker.be pancarte voorbij met de SEO content

**Comment by pbelmans** [comment]
Die achtergrond shading zorgt ervoor dat PNG waarschijnlijk niet zo'n goed idee is, het wordt een JPG dus.

**Comment by pbelmans** [comment]
https://twitter.com/pbelmans/status/1240547955595194368 duidt het probleem aan: hij laadt het van maakjemondmasker.be dus.

**Comment by woutervddn** [comment]
> Die achtergrond shading zorgt ervoor dat PNG waarschijnlijk niet zo'n goed idee is, het wordt een JPG dus.

thx! ging net hetzelfde voorstellen. ik heb een compressiescript dat goed werkt, maar deze png kreeg hij mr 10% kleiner... :) eens open geklikt en dacht hetzelfde.

**Comment by pbelmans** [comment]
Heeft er ooit een redirect gestaan op maskermatch.be naar maakjemondmasker.be? Want Twitter blijft naar de verkeerde URL linken (en de verkeerde afbeelding gebruiken): https://twitter.com/pbelmans/status/1240552876398837760

**Comment by pbelmans** [comment]
Lijkt in orde te zijn nu.
