### ISSUE TITLE
GDPR (?)

### ISSUE THREAD

**Issue by lebomb** [MakeInBelgium/maskermatch#9]
Op aanvraag van #corona-maskermatch: 

Bekijken hoe we omgaan met persoonsgegevens. (Google Forms adressen, cookie popup bij openen site, ... )

**Comment by jellevictoor** [comment]
1. een overzicht hebben van waar we welke data opslaan, zodat we kunnen ingrijpen als we een gdpr request krijgen. er gaat ook een gdpr aanspreekpunt nodig zijn
2. alle google forms in de eu hosten (dit is een optie die relatief diep verborgen zit)
3. cookie wall voorzien


waarschijnlijk mis ik nog zaken. ik denk dat dit breder gaat dan maskermatch, maar voor alle initiatieven van toepassing is.

**Comment by woutervddn** [comment]
https://github.com/MakeInBelgium/maskermatch/pull/20

**Comment by pbelmans** [comment]
Zie #20. Het GDPR aanspreekpunt is enigszins onduidelijk nu, omdat het allemaal nogal snel beweegt. Te zijner tijd kan dit aangevuld worden.

Hosting van de forms in de EU is iets waar @woutervddn even naar kan kijken best.
